package types

type HeaderName string

const (
	HeaderNameVia                     HeaderName = "Via"
	HeaderNameFrom                    HeaderName = "From"
	HeaderNameTo                      HeaderName = "To"
	HeaderNameCallID                  HeaderName = "Call-ID"
	HeaderNameCSeq                    HeaderName = "CSeq"
	HeaderNameContact                 HeaderName = "Contact"
	HeaderNameContentType             HeaderName = "Content-Type"
	HeaderNameContentLength           HeaderName = "Content-Length"
	HeaderNameUserAgent               HeaderName = "User-Agent"
	HeaderNameMaxForwards             HeaderName = "Max-Forwards"
	HeaderNameAllow                   HeaderName = "Allow"
	HeaderNameSupported               HeaderName = "Supported"
	HeaderNameRequire                 HeaderName = "Require"
	HeaderNameExpires                 HeaderName = "Expires"
	HeaderNameAuthorization           HeaderName = "Authorization"
	HeaderNameProxyAuthorization      HeaderName = "Proxy-Authorization"
	HeaderNameWWWAuthenticate         HeaderName = "WWW-Authenticate"
	HeaderNameProxyAuthenticate       HeaderName = "Proxy-Authenticate"
	HeaderNameRecordRoute             HeaderName = "Record-Route"
	HeaderNameRoute                   HeaderName = "Route"
	HeaderNameWarning                 HeaderName = "Warning"
	HeaderNameAnswerMode              HeaderName = "Answer-Mode"
	HeaderNameAccept                  HeaderName = "Accept"
	HeaderNameAcceptEncoding          HeaderName = "Accept-Encoding"
	HeaderNameAcceptLanguage          HeaderName = "Accept-Language"
	HeaderNameAllowEvents             HeaderName = "Allow-Events"
	HeaderNameEvent                   HeaderName = "Event"
	HeaderNameSubscriptionState       HeaderName = "Subscription-State"
	HeaderNameReason                  HeaderName = "Reason"
	HeaderNameContentDisposition      HeaderName = "Content-Disposition"
	HeaderNameX_MSXF_DID              HeaderName = "X-MSXF-DID"
	HeaderNameX_MSXF_FAILOVER_GROUP   HeaderName = "X-MSXF-FAILOVER-GROUP"
	HeaderNameX_sectet_key            HeaderName = "X-Sectet_key"
	HeaderNameX_sectet_flag           HeaderName = "X-Sectet_flag"
	HeaderNameX_sectet_algo           HeaderName = "X-Sectet_algo"
	HeaderNameX_ICC_CALL_ID           HeaderName = "X-ICC-CALL-ID"
	HeaderNameX_ICC_CALL_TYPE         HeaderName = "X-ICC-CALL-TYPE"
	HeaderNameX_ICC_MARK_PHONE_NUMBER HeaderName = "X-ICC-MARK-PHONE-NUMBER"
	HeaderNameX_ICC_CALL_RULE         HeaderName = "X-ICC-CALL-RULE"
	HeaderNameX_ICC_AUTO_ANSWER       HeaderName = "X-ICC-AUTO-ANSWER"
	HeaderNameX_FS_SUPPORT            HeaderName = "X-FS-Support"
)

type HeaderValue string
